#!/bin/bash

export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

if [ -d "$OPENSHIFT_REPO_DIR/vendor" ]; then
	echo 'Laravel dependencies already installed, Moving on...'
else
	echo 'Hang in there, we are getting ready to Install/Update Laravel dependencies'
	# Uncomment to activate composer install for Laravel on Git Push
	( echo 'Installing/Updating Laravel'; unset GIT_DIR ; cd $OPENSHIFT_REPO_DIR ; php $OPENSHIFT_DATA_DIR/composer.phar -q --no-ansi install )	
fi

