#!/bin/bash

export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

if [ -e "$OPENSHIFT_REPO_DIR/vendor" ]; then
	echo 'Laravel dependencies already installed, Moving on...'
else
	[ -d $OPENSHIFT_DATA_DIR/vendor ] || mkdir $OPENSHIFT_DATA_DIR/vendor
	ln -fs $OPENSHIFT_DATA_DIR/vendor $OPENSHIFT_REPO_DIR/vendor

	echo 'Hang in there, we are getting ready to Install/Update Laravel dependencies'
	# Uncomment to activate composer install for Laravel on Git Push
	( echo 'Installing/Updating Laravel'; unset GIT_DIR ; cd $OPENSHIFT_REPO_DIR ; php $OPENSHIFT_DATA_DIR/composer.phar --no-ansi install )	
fi

# Uncomment below to migrate your databases
#
#echo "Migrating databases"
#cd $OPENSHIFT_REPO_DIR
#php artisan migrate --package=cartalyst/sentry
#php artisan migrate
